### ISSUE TITLE
Notes Modal Overlap

### ISSUE THREAD

**Issue by bryantal** [BCStudentSoftwareDevTeam/cas#281]
**[Original report](https://bitbucket.org/laborstudents/cas-flask/issue/281) by Sher Sanginov (Bitbucket: [shersanginov](https://bitbucket.org/shersanginov), GitHub: [sanginovs](https://github.com/sanginovs)).**

----------------------------------------

If user clicks on another note, previous note should close automatically. Also, Insert <x> icon to exit in the top-right of Notes model to make it more user-friendly. Currently, you can close Notes by re-clicking Notes which is not straightforward.  Fix notes on Special courses too. 
How to reproduce this bug: 

>> Go to /courses/term_id/prefix to get list of courses
>> Click on every single Notes.

>> You will see these overlaps:

![notes_overlap.png](https://bitbucket.org/repo/y4axrX/images/528859221-notes_overlap.png)

Helpful Resources:

>> Bootstrap Popovers:[https://getbootstrap.com/docs/4.1/components/popovers/](Link URL)
>> Insert close button on Popover: [https://stackoverflow.com/questions/13413057/how-to-insert-close-button-in-popover-for-bootstrap](Link URL)
>> Files affected:
>> static/local/course.js  **
>> app/templates/snips/courseElements/AdminCourseTable.html **
>> Special Courses in Course Management **

**Comment by bryantal** [comment]
**Original comment by Jamal Aw Yonis (Bitbucket: [awyoonisj](https://bitbucket.org/awyoonisj), GitHub: [jawyoonis](https://github.com/jawyoonis)).**

----------------------------------------

Hey @sanginovs  is this issue finished?

**Comment by bryantal** [comment]
**Original comment by Sher Sanginov (Bitbucket: [shersanginov](https://bitbucket.org/shersanginov), GitHub: [sanginovs](https://github.com/sanginovs)).**

----------------------------------------

@jawyoonis no it's not. You can take over if you want

**Comment by Sandesh-L** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CAS #281 Notes Modal Overlap](https://trello.com/c/npln3ztL/251-cas-281-notes-modal-overlap)

**Comment by BrianRamsay** [comment]
released
