### ISSUE TITLE
Special Topics courses don't show instructor

### ISSUE THREAD

**Issue by bryantal** [BCStudentSoftwareDevTeam/cas#312]
**[Original report](https://bitbucket.org/laborstudents/cas-flask/issue/312) by Scott Heggen (Bitbucket: [sheggen](https://bitbucket.org/sheggen), GitHub: [sheggen](https://github.com/sheggen)).**

----------------------------------------

On the /courses page there is a special topics course for GEO 186. The instructor's name is in the system (confirmed by seeing it in the edit modal), but it is not showing on the front end:

![Screen Shot 2019-02-12 at 2.25.03 PM.png](https://bitbucket.org/repo/y4axrX/images/2409556458-Screen%20Shot%202019-02-12%20at%202.25.03%20PM.png)

Looks like display problem only. Data is intact.

**Comment by bryantal** [comment]
**Original comment by Scott Heggen (Bitbucket: [sheggen](https://bitbucket.org/sheggen), GitHub: [sheggen](https://github.com/sheggen)).**

----------------------------------------

For clarity, the image above doesn't show an instructor after the blue Submitted label, but there is an instructor assigned to the course.

**Comment by Sandesh-L** [comment]
Tyler, Lisandro, and Sandesh are working on this.

**Comment by escalerapadronl** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CAS #312: Special Topics courses don't show instructor](https://trello.com/c/Njjz2nJF/243-cas-312-special-topics-courses-dont-show-instructor)
