### ISSUE TITLE
Both tabs appear for scheduling new courses panel at bottom of courses page

### ISSUE THREAD

**Issue by bryantal** [BCStudentSoftwareDevTeam/cas#338]
**[Original report](https://bitbucket.org/laborstudents/cas-flask/issue/338) by Scott Heggen (Bitbucket: [sheggen](https://bitbucket.org/sheggen), GitHub: [sheggen](https://github.com/sheggen)).**

----------------------------------------

When you click the “Import Course\(s\)” tab at the bottom of the page, it is not closing the “Create a Course” tab, resulting in two tabs open. 

The UI should only show one or the other, depending on the tab selected.

**Comment by escalerapadronl** [comment]
Tried to recreate this issue but switching between the two tabs seems to be working properly.
