### ISSUE TITLE
Faculty/Staff importer skips some B-numbers

### ISSUE THREAD

**Issue by bryantal** [BCStudentSoftwareDevTeam/cas#344]
**[Original report](https://bitbucket.org/laborstudents/cas-flask/issue/344) by Scott Heggen (Bitbucket: [sheggen](https://bitbucket.org/sheggen), GitHub: [sheggen](https://github.com/sheggen)).**

----------------------------------------

B-numbers are important on the spreadsheet download, for importing courses into banner. 

‌

Some staff are not getting a b-number when they are imported. Not sure if it’s our script \(maybe works differently for staff than faculty\) or data in the AD, or something else. Take a look at the LDAP importer script as a starting point. 

‌

A few missing B-numbers:  
Chris Green

Monica Kennison

‌

**Comment by bryantal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CAS #344: Faculty/Staff importer skips some B-numbers](https://trello.com/c/V8j1LTIg/259-cas-344-faculty-staff-importer-skips-some-b-numbers)

**Comment by BrianRamsay** [comment]
@bryantal Can you check and see if this is still an issue? I suspect I fixed it accidentally when I fixed the LDAP importer to include people marked as Faculty AND Staff

**Comment by BrianRamsay** [comment]
Archiving - I don't think this is still an issue
