### ISSUE TITLE
Footer Does not Span to Bottom of the Page

### ISSUE THREAD

**Issue by zachneill** [BCStudentSoftwareDevTeam/cas#390]
The footer on the home page does not span to the bottom of the page. It is 2/3rd of the way through the page. The room preferences tab also noticeably has this issue

**Comment by Sandesh-L** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CAS #390 Footer Does not Span to Bottom of the Page](https://trello.com/c/DrmQTc3K/246-cas-390-footer-does-not-span-to-bottom-of-the-page)
