### ISSUE TITLE
Special Topics Course Faculty Credit Load not displaying all options in Course management

### ISSUE THREAD

**Issue by escalerapadronl** [BCStudentSoftwareDevTeam/cas#393]
When a special topics course is added, the options for the Faculty Credit Load selectpicker are from .25 to 2.0. However, when an admin goes to approve/deny the special topics course in Course Management, the selectpicker for Faculty Credit Load only shows .25 to 1.5. This causes the selectpicker to default to the first option (.25), completely changing how many credits the class provides. 

![Screen Shot 2021-06-04 at 9 52 41 AM](https://user-images.githubusercontent.com/46552219/120812916-6e490480-c51b-11eb-8177-d1c5133cb4a1.png)

![Screen Shot 2021-06-04 at 9 53 51 AM](https://user-images.githubusercontent.com/46552219/120812955-7608a900-c51b-11eb-84e5-e6bf88bd285b.png)

**Comment by Sandesh-L** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CAS #393 Special Topics Course Faculty Credit Load not displaying all options in Course management](https://trello.com/c/M2yi0vVf/249-cas-393-special-topics-course-faculty-credit-load-not-displaying-all-options-in-course-management)

**Comment by bryantal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CAS #354: Special Topics courses do not acknowledge cross-listing](https://trello.com/c/uAMQg8bp/256-cas-354-special-topics-courses-do-not-acknowledge-cross-listing)
