### ISSUE TITLE
footer overlaps with courses, term management buttons

### ISSUE THREAD

**Issue by zachneill** [BCStudentSoftwareDevTeam/cas#410]
The footer is overlaid over some of the content of the site. The submit button for creating a course is noticeably covered up, and some of the bottom-most buttons when clicking throw term management are mostly covered up.

**Comment by zachneill** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CAS #410: footer overlaps with courses, term management buttons](https://trello.com/c/9FlKo9Vm/264-cas-410-footer-overlaps-with-courses-term-management-buttons)

**Comment by sheggen** [comment]
Reviving this issue.
