### ISSUE TITLE
Room Select

### ISSUE THREAD

**Issue by bryantal** [BCStudentSoftwareDevTeam/cas#57]
**[Original report](https://bitbucket.org/laborstudents/cas-flask/issue/57) by Cody Myers (Bitbucket: [cody_myers](https://bitbucket.org/cody_myers), GitHub: [myersCody](https://github.com/myersCody)).**

----------------------------------------

We need to create some text that informs the users that just because they select a room, that does not guarantee them that they will receive the room.

**Comment by bryantal** [comment]
**Original comment by Guillermo ramos (Bitbucket: [guillermo_ramos](https://bitbucket.org/guillermo_ramos), GitHub: [memo330179](https://github.com/memo330179)).**

----------------------------------------

commit df38172 adds a popup warning when dropdown is open

**Comment by bryantal** [comment]
**Original comment by Guillermo ramos (Bitbucket: [guillermo_ramos](https://bitbucket.org/guillermo_ramos), GitHub: [memo330179](https://github.com/memo330179)).**

----------------------------------------

We need to decide what would be a good message to show.

**Comment by bryantal** [comment]
**Original comment by Guillermo ramos (Bitbucket: [guillermo_ramos](https://bitbucket.org/guillermo_ramos), GitHub: [memo330179](https://github.com/memo330179)).**

----------------------------------------

We need a good message to show.

**Comment by sheggen** [comment]
I believe this is no longer an issue.
